### ISSUE TITLE
The first and last pages of the contents need links

### ISSUE THREAD

**Issue by hamle365** [MattHeard/Dendrite#244]

**Comment by MattHeard** [comment]
1. Count number of StoryBeginning entities in the datastore.
2. Divide by the number of stories to display on each contents page.
3. If there is a remainder, add 1. This is the number of the last page of contents.
4. The number of the first page of contents is always 1.

**Comment by MattHeard** [comment]
Resolved by commit fbc29c909e6c654305759d706f4b6750ced911cb.
