### ISSUE TITLE
Table of Contents "Back to the First Page" arrow redirects incorrectly on filtered Tables of Contents

### ISSUE THREAD

**Issue by hamle365** [MattHeard/Dendrite#249]
When the Table of Contents is filtered by genre, when you click the "back to the first page" arrow of the list, it takes you back to the first page of the entire ToC rather than the first page of the filtered ToC.
![final page fanfic browse](https://cloud.githubusercontent.com/assets/7555291/10563058/8268d602-75d5-11e5-9b0a-a48949742234.PNG)
![first page table contents](https://cloud.githubusercontent.com/assets/7555291/10563059/826ee01a-75d5-11e5-85da-38d6cd5adf03.png)

**Comment by MattHeard** [comment]
Fixed in c25dced28fe36c44155290655600f03ecdafa333
